package de.kevin.vmaxdashboard

data class ByteCandidate(
    val characteristic: String,
    val byteIndex: Int,
    val beforeValue: Int,
    val activeValue: Int,
    val score: Int
)

data class BleChannelState(
    val channel: String = "",
    val service: String = "1500",
    val title: String = "",
    val meaning: String = "",
    val knowledge: String = "",
    val hex: String = "",
    val changedBytes: String = "–",
    val packetCount: Int = 0,
    val active: Boolean = false,
    val lastSeenMs: Long = 0L
)

data class ScooterState(
    val scanning: Boolean = false,
    val connected: Boolean = false,
    val status: String = "Bereit",
    val deviceName: String = "BT638",
    val address: String = "",
    val batteryPercent: Int? = null,
    val voltageV: Double? = null,
    val currentA: Double? = null,
    val motorTemperatureC: Double? = null,
    val batteryTemperatureC: Double? = null,
    val temperatureC: Double? = null,
    val speedKmh: Double? = null,
    val driveRaw: Int? = null,
    val motorLoadRaw: Int? = null,
    val batteryStateRaw: Int? = null,
    val accessoryByte0: Int? = null,
    val accessoryByte3: Int? = null,
    val tripDistanceKm: Double? = null,
    val odometerKm: Double? = null,
    val rssi: Int? = null,
    val leftIndicator: Boolean = false,
    val rightIndicator: Boolean = false,
    val lightOn: Boolean = false,
    val brakeActive: Boolean = false,
    val lockActive: Boolean? = null,
    val charging: Boolean? = null,
    val lastCharacteristic: String = "",
    val lastRawHex: String = "",
    val lastChangedBytes: String = "–",
    val rawPackets: Map<String, String> = emptyMap(),
    val analysisPhase: String = "Bereit",
    val analysisPhaseNumber: Int = 0,
    val packetTotal: Int = 0,
    val packetsPerSecond: Double = 0.0,
    val lastPacketAt: Long = 0L,
    val currentPowerW: Double? = null,
    val maxSpeedKmh: Double? = null,
    val maxPowerW: Double? = null,
    val sessionStartedAt: Long = 0L,
    val channels: List<BleChannelState> = emptyList(),
    val labRunning: Boolean = false,
    val labPhase: String = "Bereit",
    val labAction: String = "",
    val labCandidates: List<ByteCandidate> = emptyList(),
    val encryptedReports: Int = 0,
    val lastExportMessage: String = "",
    val recordingActive: Boolean = false,
    val recordingPaused: Boolean = false,
    val recordingStartedAt: Long = 0L,
    val recordingPacketCount: Int = 0,
    val markerCount: Int = 0,
    val lastMarker: String = "",
    val autoAnalysisFindings: List<MeasurementFinding> = emptyList(),
    val learningProfileCount: Int = 0,
    val sessionHistoryCount: Int = 0,
    val lastSessionFolder: String = "",
    val aiDecoderRuleCount: Int = 0,
    val aiDecoderConfirmedRules: Int = 0,
    val aiDecoderRevision: String = "",
    val aiDecoderSource: String = "Noch kein KI-Profil",
    val aiDecoderSignals: Set<String> = emptySet(),
    val motorTuningSupported: Boolean = false,
    val motorTuningReadAvailable: Boolean = false,
    val motorTuningWriteAvailable: Boolean = false,
    val motorTuningBusy: Boolean = false,
    val motorTuningStatus: String = "Noch nicht geprüft",
    val motorTuningProtocol: MotorTuningProtocolMode = MotorTuningProtocolMode.UNKNOWN,
    val motorTuningProfiles: List<MotorTuningProfile> = emptyList(),
    val motorTuningOriginalProfiles: List<MotorTuningProfile> = emptyList(),
    val motorTuningLastPacket: String = "",
    val motorTuningLastReadRaw: String = "",
    val motorTuningLastVerified: Boolean? = null,
    val log: List<String> = emptyList()
)
